[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
ubiquity = { git = "https://gitlab.com/Blockdaemon/ubiquity/ubiquity-rust-client", branch = "v1" }
tokio = { version = "1.8.0", features = ["full"] }
