stages:
  - build-examples
  - test

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:1.63.0"

build-examples:
  stage: build-examples
  script: make examples

# Use cargo to test the project
test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
    - rustup component add clippy
    - cargo clippy --all --all-features --tests

# Run cargo clippy
test:clippy:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy --all --all-features --tests
