stages:
  - generate
  - test

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:1.53.0"

generate:
  stage: generate
  script:
    - apt-get update -y
    - apt-get install default-jre -y
    # TODO -> Have the jar url in a env/config variable somewhere to use it in the Makefile as well
    - wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.2.0/openapi-generator-cli-5.2.0.jar -O openapi-generator-cli.jar
    # Send to /dev/null to suppress very large output
    - make > /dev/null
    - git config --global user.name "Mr.Roboto 🤖"
    - git config --global user.email "mrRoboto@blockdaemon.com"
    - git add ./ubiquity ./docs
    - git commit -m "UB-00 Updating generated code with changes from ${CI_JOB_ID}"
    - git push http://gitlab-ci-token:${AUTH_TOKEN_UBIQUITY_RUST_CLIENT}@gitlab.com/Blockdaemon/ubiquity/ubiquity-rust-client.git HEAD:master
  only:
      refs:
        - master
      changes:
        - spec/openapi.yaml

# Use cargo to test the project
test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
